### PR TITLE
fix: better tonemapping for the comp script

### PR DESCRIPTION
**Pull request by gaitas13**
Updated the comp script so that it uses better tonemapping defaults

### CODE REVIEW

**Comment by Ravencentric** [comment]
You'll have to provide some comps and explanation on why it's better.

**Comment by gaitas13** [comment]
[the comp you requested](https://slow.pics/c/MZeyw80x)

about tone mapping mode:
1 (rgb, your previous one) while preventing clipping, [distorts colors](https://github.com/haasn/libplacebo/blob/258cf937bfdf56f188bf027f857866cf396d8f6b/src/include/libplacebo/shaders/colorspace.h#L203)
3 (hybrid) [uses a 2.4 gamma curve](https://github.com/haasn/libplacebo/blob/258cf937bfdf56f188bf027f857866cf396d8f6b/src/include/libplacebo/shaders/colorspace.h#L212C1-L212C1), which may make colors look better

about gamut mode:
3 (darken) [seems to provide the best balance for preserving colors](https://github.com/haasn/libplacebo/blob/258cf937bfdf56f188bf027f857866cf396d8f6b/src/include/libplacebo/shaders/colorspace.h#L233)

about intent:
0 (perceptual) uses [perceptual metrics](https://github.com/haasn/libplacebo/blob/61c1c589f66bd913a0680d741a24e32894ed127b/src/include/libplacebo/colorspace.h#L425), which i think is the better option but i may be biased

hope this helps

**Comment by gaitas13** [comment]
i also created comps for [enter the dragon](https://slow.pics/c/3UwbCuRM) and [mask of the phantasm](https://slow.pics/c/870Fi1mK), while also making individual comps for each argument i added/changed using the wiki script as a base
[tone mapping mode](https://slow.pics/c/8NCvoZN8)
[gamut mode](https://slow.pics/c/sDuVq3q1)
[intent](https://slow.pics/c/OQbBWivH)

**Comment by Ravencentric** [comment]
Thank you, I'll take a look at this when I have time.

**Comment by Ravencentric** [comment]
Looking at the comps, there's no SDR for reference in any of them

**Comment by gaitas13** [comment]
i can redo the cyberpunk one, the other two use entirely different transfer for their hdr and sdr with years between them

**Comment by Ravencentric** [comment]
That would be great

**Comment by gaitas13** [comment]
[cyberpunk sdr](https://slow.pics/c/JSIx45AD)

**Pull request merged**
