### PR TITLE
feat: redesign sourcing/streaming.md and getting-started/anime.md

### PR DESCRIPTION
**Pull request by ricky8k**
Redesign for sourcing/streaming.md and getting-started/anime.md to simplify information and utilize Retype's components for a more organized look.

Majority of the documentation was rewritten to make it easier to understand for the user, while also maintaining a similar or better level of information.

Some other changes include:
- Reducing information that isn't necessary in anime.md, directing users to the main page if they wish to learn more.
- Fixing links to pages that have been moved or removed.
- Recommending the user a reliable content/ad blocker in streaming.md and anime.md.
- Warnings (i.e. copyright notices through torrenting, fake streaming sites).
- Amending grammatical and formatting errors.

[These changes can be previewed live here.](https://ricky8k.github.io/thewiki/)

### CODE REVIEW

**Comment by Ravencentric** [comment]
most of the changes are great, although I do think there's a bit too much going on at times
image
Like here, 4 notes/warnings being relatively close are sort of cluttering

You should also skip adding bold in warnings/notes since they already attract your attention without bold.

**Comment by ricky8k** [comment]
Thanks for the feedback. I just pushed a commit to the redesign branch reducing the number of notes and introducing your formatting changes. You should be able to preview them from the same page.

In streaming.md, I've removed all notes and kept only warnings, as I believe they are most important. For instance, the links to unofficial/official streams now appear at the end of _Popular Sites_. The note on additional factors at the end of the page was removed and formatted to look similar to anime.md's redirect in each section.
firefox_l1SCfywZXJ

In anime.md, I merged the two notes in _Streaming_ into one. I've also removed the note on using GoodbyeDPI in _Torrenting_, as I believe that this can be added to the main page in future instead.

**Comment by Ravencentric** [comment]
Happy with the changes, thank you for contributing. Also, feel free to join our [discord](https://discord.gg/snackbox) and ping me `@ravencentric` if you are interested in working on the wiki together :D. Regardless, all future PRs are welcome!

**Comment by ricky8k** [comment]
Apologies for being late. I joined your Discord server awhile ago, my Discord tag is `@derpie.`

**Pull request merged**
